_commit: 90378fa1c909a9320b0cf4525bdf30dc16e5d72f
_src_path: gh:AlejandroBaron/alex-baron-project-template
author_email: alebaro@example.com
author_name: Alejandro Baron
description: World model for Pong game
package_name: neural_pong
project_name: neural-pong
python_version: "3.10"
